# Generated by Django 2.2 on 2020-03-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit', models.IntegerField()),
                ('motorcycle', models.IntegerField()),
                ('car', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit', models.IntegerField()),
                ('motorcycle', models.IntegerField()),
                ('car', models.IntegerField()),
                ('pedestrians', models.IntegerField()),
                ('bicyclist', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Injuries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit', models.IntegerField()),
                ('motorcycle', models.IntegerField()),
                ('car', models.IntegerField()),
                ('pedestrians', models.IntegerField()),
                ('bicyclist', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subpoena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subpoena', models.IntegerField()),
                ('covid_subpoena', models.IntegerField()),
            ],
        ),
    ]
