# Generated by Django 2.2 on 2020-03-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coexistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contempts', models.IntegerField()),
                ('establishments', models.IntegerField()),
                ('underage', models.IntegerField()),
                ('domestic_violence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thefts_persons', models.IntegerField()),
                ('thefts_commerce', models.IntegerField()),
                ('personal_injuries', models.IntegerField()),
                ('domestic_violence', models.IntegerField()),
                ('homicides', models.IntegerField()),
            ],
        ),
    ]
