# Generated by Django 2.2 on 2020-03-25 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security_conv', '0002_remove_security_domestic_violence'),
    ]

    operations = [
        migrations.AddField(
            model_name='coexistence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='security',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
