# Generated by Django 2.2 on 2020-03-27 05:08

import datetime
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('security_conv', '0004_auto_20200325_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coexistence',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='security',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
