version: '3'

networks:
    main_net:

volumes:
    postgres:
    redis_data:
    node:
    cube:

services:
    nginx: 
        image: nginx:stable
        volumes:
          - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
          - 444:443
        depends_on:
          - django
        networks:
            - main_net

    postgres:
        image: postgres:9.6.17
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file: .secret
        ports:
            - "5432:5432"
        networks:
            - main_net

    django:
        build: 
            context: ./services/django
            dockerfile: Dockerfile
        command: ["python","manage.py","runserver", "0.0.0.0:8000", "--noreload"]
        volumes:
            - "./services/django:/api"
            
        depends_on:
            - postgres
        environment:
            PYTHONPATH: /api
            PYTHONUNBUFFERED: "True"
            DEBUG: "True"
        env_file: .secret
        ports:
            - "8000:8000"
        networks:
            - main_net
    cubejs:
        build: ./services/cubejs
        command: npm run dev
        env_file:
            - ./services/cubejs/.env
        volumes:
            - ./services/cubejs:/usr/src/app
            # - cube:/usr/src/app/node_modules
        depends_on: 
            - redis
        ports:
            - "4000:4000"
        networks:
            - main_net

    frontend:
        image: frontend:dev
        build: 
            context: ./services/django
            dockerfile: Dockerfile.frontend
        command: npm run dev
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./services/django:/usr/src/app
            - node:/usr/src/app/node_modules
            # - ./services/django/logs:/root/.npm/_logs
        expose:
            - "9000"
        networks:
            - main_net
    
    redis:
        image: redis:3.2-alpine
        restart: always
        volumes:
            - redis_data:/data
        expose:
            - "6379"
        networks:
            - main_net 
    
