# Generated by Django 2.2 on 2020-03-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_networks', models.IntegerField()),
                ('rush', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('FLO', 'Floridablanca'), ('BOS', 'Bosconia'), ('MOR', 'Morrorico'), ('LFL', 'La Flora')], default='TON', max_length=20)),
                ('coagultant_available', models.IntegerField()),
                ('coagulant_estimated_duration', models.IntegerField()),
                ('disinfectant_available', models.IntegerField()),
                ('disinfectan_estimated_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReinstallationWaterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disconnection', models.IntegerField()),
                ('pending', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('FLO', 'Floridablanca'), ('BOS', 'Bosconia'), ('MOR', 'Morrorico'), ('LFL', 'La Flora'), ('TOT', 'Total')], default='TON', max_length=20)),
                ('plant_capacity', models.IntegerField()),
                ('flow_treated', models.IntegerField()),
                ('flow_delivered', models.IntegerField()),
                ('daily_production', models.IntegerField()),
                ('consumption_per_capita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('TON', 'Tona'), ('RFR', 'Rio Frío'), ('SUR', 'Suratá')], default='TON', max_length=20)),
                ('flow', models.IntegerField()),
                ('turbidity', models.IntegerField()),
                ('color', models.IntegerField()),
            ],
        ),
    ]
