# Generated by Django 2.2 on 2020-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_auto_20200325_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterproduction',
            name='location',
            field=models.CharField(choices=[('FLO', 'Floridablanca'), ('BOS', 'Bosconia'), ('MOR', 'Morrorico'), ('LFL', 'La Flora')], default='TON', max_length=20),
        ),
    ]
