export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// SECURITY
export const GET_SECURITY = "GET_SECURITY";
export const DELETE_SECURITY = "DELETE_SECURITY";
export const ADD_SECURITY = "ADD_SECURITY";
export const CREATE_SECURITY = "CREATE_SECURITY";
export const GET_COEXISTENCE = "GET_COEXISTENCE";
export const DELETE_COEXISTENCE = "DELETE_COEXISTENCE";
export const ADD_COEXISTENCE = "ADD_COEXISTENCE";
export const CREATE_COEXISTENCE = "CREATE_COEXISTENCE";

// SUPPLYING
export const GET_SUPPLYING = "GET_SUPPLYING";
export const DELETE_SUPPLYING = "DELETE_SUPPLYING";
export const ADD_SUPPLYING = "ADD_SUPPLYING";
export const CREATE_SUPPLYING = "CREATE_SUPPLYING";
export const GET_TARGET_VOLUME = "GET_TARGET_VOLUME";
export const DELETE_TARGET_VOLUME = "DELETE_TARGET_VOLUME";
export const ADD_TARGET_VOLUME = "ADD_TARGET_VOLUME";
export const CREATE_TARGET_VOLUME = "CREATE_TARGET_VOLUME";

// TRAFFIC
export const GET_ACCIDENT = "GET_ACCIDENT";
export const DELETE_ACCIDENT = "DELETE_ACCIDENT";
export const ADD_ACCIDENT = "ADD_ACCIDENT";
export const CREATE_ACCIDENT = "CREATE_ACCIDENT";
export const GET_DEATH = "GET_DEATH";
export const DELETE_DEATH = "DELETE_DEATH";
export const ADD_DEATH = "ADD_DEATH";
export const CREATE_DEATH = "CREATE_DEATH";
export const GET_INJURIES = "GET_INJURIES";
export const DELETE_INJURIES = "DELETE_INJURIES";
export const ADD_INJURIES = "ADD_INJURIES";
export const CREATE_INJURIES = "CREATE_INJURIES";
export const GET_METROLINEA = "GET_METROLINEA";
export const DELETE_METROLINEA = "DELETE_METROLINEA";
export const ADD_METROLINEA = "ADD_METROLINEA";
export const CREATE_METROLINEA = "CREATE_METROLINEA";
export const GET_SUBPOENA = "GET_SUBPOENA";
export const DELETE_SUBPOENA = "DELETE_SUBPOENA";
export const ADD_SUBPOENA = "ADD_SUBPOENA";
export const CREATE_SUBPOENA = "CREATE_SUBPOENA";

// WATER
export const GET_DAMAGE_RATE = "GET_DAMAGE_RATE";
export const DELETE_DAMAGE_RATE = "DELETE_DAMAGE_RATE";
export const ADD_DAMAGE_RATE = "ADD_DAMAGE_RATE";
export const CREATE_DAMAGE_RATE = "CREATE_DAMAGE_RATE";
export const GET_INVENTORY = "GET_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const ADD_INVENTORY = "ADD_INVENTORY";
export const CREATE_INVENTORY = "CREATE_INVENTORY";
export const GET_REINSTALLATION_RATER_SERVICE = "GET_REINSTALLATION_RATER_SERVICE";
export const DELETE_REINSTALLATION_RATER_SERVICE = "DELETE_REINSTALLATION_RATER_SERVICE";
export const ADD_REINSTALLATION_RATER_SERVICE = "ADD_REINSTALLATION_RATER_SERVICE";
export const CREATE_REINSTALLATION_RATER_SERVICE = "CREATE_REINSTALLATION_RATER_SERVICE";
export const GET_WATER_PRODUCTION = "GET_WATER_PRODUCTION";
export const DELETE_WATER_PRODUCTION = "DELETE_WATER_PRODUCTION";
export const ADD_WATER_PRODUCTION = "ADD_WATER_PRODUCTION";
export const CREATE_WATER_PRODUCTION = "CREATE_WATER_PRODUCTION";
export const GET_WATER_SOURCES = "GET_WATER_SOURCES";
export const DELETE_WATER_SOURCES = "DELETE_WATER_SOURCES";
export const ADD_WATER_SOURCES = "ADD_WATER_SOURCES";
export const CREATE_WATER_SOURCES = "CREATE_WATER_SOURCES";