export const GET_SECURITY = "GET_SECURITY";
export const DELETE_SECURITY = "DELETE_SECURITY";
export const ADD_SECURITY = "ADD_SECURITY";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";