# Generated by Django 2.2 on 2020-03-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetVolumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlatinco', models.IntegerField()),
                ('guajira', models.IntegerField()),
                ('bolivar', models.IntegerField()),
                ('cesar', models.IntegerField()),
                ('magdalena', models.IntegerField()),
                ('norte_santander', models.IntegerField()),
                ('magdalena_medio', models.IntegerField()),
                ('nororiente_antioqueño', models.IntegerField()),
                ('provincia_guanentina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField()),
                ('first_out', models.IntegerField()),
                ('second_out', models.IntegerField()),
                ('collected', models.IntegerField()),
            ],
        ),
    ]
