# Generated by Django 2.2 on 2020-03-25 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetvolumes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
